services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=first
      - DATABASE_USER=root
      - DATABASE_PASSWORD=kali
    depends_on:
      - db
    networks:
      custom_network:
        ipv4_address: 172.20.0.22  

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: first
      MYSQL_USER: kali
      MYSQL_PASSWORD: kali
      MYSQL_ROOT_PASSWORD: kali
    volumes:
      - db_data:/var/lib/mysql
    networks:
      custom_network:
        ipv4_address: 172.20.0.23

  open-appsec-agent:
    image: ghcr.io/openappsec/agent:latest
    container_name: open-appsec-agent
    ipc: host
    environment:
      - registered_server=NGINX
      - AGENT_TOKEN=cp-81bf9e06-4d89-40c1-a05a-f7303db025fe2a9f9f6b-f236-4939-94ca-4cab693b4320
    volumes:
      - ./openappsec/agent_config:/etc/cp/conf
      - ./openappsec/agent_data:/etc/cp/data
      - ./openappsec/agent_debug:/etc/cp/nano_agent
    networks:
      - custom_network
  open-appsec-nginx:
    image: ghcr.io/openappsec/nginx-attachment:latest
    container_name: open-appsec-nginx
    depends_on:
      - web
      - open-appsec-agent
    ipc: host
    ports:
      - "80:80"
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/default.conf
    networks:
      custom_network:        
        ipv4_address: 172.20.0.24

volumes:
  db_data: {}

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
